package com.exam;
// Generated Jun 17, 2019 9:08:36 AM by Hibernate Tools 4.3.1



/**
 * Cart generated by hbm2java
 */
public class Cart  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String productname;
     private String brand;
     private Integer qty;
     private Integer total;
     private Integer stockremain;
     private String orderdate;

    public Cart() {
    }

    public Cart(String username, String productname, String brand, Integer qty, Integer total, Integer stockremain, String orderdate) {
       this.username = username;
       this.productname = productname;
       this.brand = brand;
       this.qty = qty;
       this.total = total;
       this.stockremain = stockremain;
       this.orderdate = orderdate;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Integer getTotal() {
        return this.total;
    }
    
    public void setTotal(Integer total) {
        this.total = total;
    }
    public Integer getStockremain() {
        return this.stockremain;
    }
    
    public void setStockremain(Integer stockremain) {
        this.stockremain = stockremain;
    }
    public String getOrderdate() {
        return this.orderdate;
    }
    
    public void setOrderdate(String orderdate) {
        this.orderdate = orderdate;
    }




}


