package com.exam;
// Generated Jun 17, 2019 9:08:36 AM by Hibernate Tools 4.3.1



/**
 * Comments generated by hbm2java
 */
public class Comments  implements java.io.Serializable {


     private int id;
     private Integer postid;
     private String username;
     private String comments;

    public Comments() {
    }

	
    public Comments(int id) {
        this.id = id;
    }
    public Comments(int id, Integer postid, String username, String comments) {
       this.id = id;
       this.postid = postid;
       this.username = username;
       this.comments = comments;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Integer getPostid() {
        return this.postid;
    }
    
    public void setPostid(Integer postid) {
        this.postid = postid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getComments() {
        return this.comments;
    }
    
    public void setComments(String comments) {
        this.comments = comments;
    }

}


