package com.exam;
// Generated Jun 17, 2019 9:08:36 AM by Hibernate Tools 4.3.1



/**
 * Member generated by hbm2java
 */
public class Member  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String email;
     private String contact;
     private String password;
     private String address;
     private String image;

    public Member() {
    }

    public Member(String name, String email, String contact, String password, String address, String image) {
       this.name = name;
       this.email = email;
       this.contact = contact;
       this.password = password;
       this.address = address;
       this.image = image;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


