package com.exam;
// Generated Jun 17, 2019 9:08:36 AM by Hibernate Tools 4.3.1



/**
 * Userpost generated by hbm2java
 */
public class Userpost  implements java.io.Serializable {


     private int postid;
     private String username;
     private String posts;
     private String image;

    public Userpost() {
    }

	
    public Userpost(int postid) {
        this.postid = postid;
    }
    public Userpost(int postid, String username, String posts, String image) {
       this.postid = postid;
       this.username = username;
       this.posts = posts;
       this.image = image;
    }
   
    public int getPostid() {
        return this.postid;
    }
    
    public void setPostid(int postid) {
        this.postid = postid;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPosts() {
        return this.posts;
    }
    
    public void setPosts(String posts) {
        this.posts = posts;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }




}


