package com.exam;
// Generated Jun 17, 2019 9:08:36 AM by Hibernate Tools 4.3.1



/**
 * Wishlist generated by hbm2java
 */
public class Wishlist  implements java.io.Serializable {


     private Integer id;
     private String username;
     private String contact;
     private String productname;
     private String brand;
     private String dates;

    public Wishlist() {
    }

    public Wishlist(String username, String contact, String productname, String brand, String dates) {
       this.username = username;
       this.contact = contact;
       this.productname = productname;
       this.brand = brand;
       this.dates = dates;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public String getProductname() {
        return this.productname;
    }
    
    public void setProductname(String productname) {
        this.productname = productname;
    }
    public String getBrand() {
        return this.brand;
    }
    
    public void setBrand(String brand) {
        this.brand = brand;
    }
    public String getDates() {
        return this.dates;
    }
    
    public void setDates(String dates) {
        this.dates = dates;
    }




}


